export const permissions = {
  HOSPITAL_VIEW: "HOSPITAL_VIEW",
  HOSPITAL_CREATE: "HOSPITAL_CREATE",
  HOSPITAL_UPDATE: "HOSPITAL_UPDATE",
  HOSPITAL_ACTIVATE: "HOSPITAL_ACTIVATE",
  HOSPITAL_DEACTIVATE: "HOSPITAL_DEACTIVATE",
  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_ENABLE: "DEPARTMENT_ENABLE",
  DEPARTMENT_DISABLE: "DEPARTMENT_DISABLE",
  HOSPITAL_DEPARTMENT_MANAGE: "HOSPITAL_DEPARTMENT_MANAGE",
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  ACTIVITY_VIEW: "ACTIVITY_VIEW",
  PLATFORM_SETTINGS_MANAGE: "PLATFORM_SETTINGS_MANAGE",
} as const;

export const rolePermissions = {
  SUPER_ADMIN: Object.values(permissions),
};
